### ISSUE TITLE
pstack lxcfs process ，get 1000+ threads

### ISSUE THREAD

**Issue by hfeng101** [lxc/lxcfs#471] opened 2021-07-20 12:24 UTC
we have found our container answer my cmd like "top/ps/free" very slowly, by using pstack attach the lxcfs process，we have got 1000+ threads, and by using strace attach  the  cmd "top/ps/free", we found that the futex have been locked forever.

pstack info 
![pstack](https://user-images.githubusercontent.com/5158183/126323243-644b0387-ab45-4198-8a62-28ecfd2c114b.png)

futex locked info
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0
futex(0x556b5a3a0508, FUTEX_WAIT_PRIVATE, 0, NULL) = 0

**Comment by hfeng101** [comment] 2021-07-20 12:24
may someone can help please?

**Comment by brauner** [comment] 2021-07-20 12:26
Hm... is this a deadlock in `libfuse2`? Can you possibly compile against `libfuse3` and see whether you can reproduce?

**Comment by nkshirsagar** [comment] 2023-01-04 08:47
Hello @brauner 

Im seeing a situation where an openstack management node has panicked due to hung task, with all fuse tasks waiting on fuse_simple_request()->request_wait_answer(), with a trace like this,

~~~
crash> bt
PID: 280234   TASK: ffff9c1f1f574000  CPU: 10   COMMAND: "mtail"
 #0 [ffffbec20dad7ba8] __schedule at ffffffff81f6d0ed
 #1 [ffffbec20dad7c30] schedule at ffffffff81f6d719
 #2 [ffffbec20dad7c50] request_wait_answer at ffffffff816fd87c
 #3 [ffffbec20dad7cb0] fuse_simple_request at ffffffff8170005c
 #4 [ffffbec20dad7ce8] fuse_direct_io at ffffffff817072cf
 #5 [ffffbec20dad7d90] fuse_file_read_iter at ffffffff81707d2b
 #6 [ffffbec20dad7e10] new_sync_read at ffffffff81580f8d
 #7 [ffffbec20dad7ea0] vfs_read at ffffffff815817d2
 #8 [ffffbec20dad7ee0] ksys_read at ffffffff81583c77
 #9 [ffffbec20dad7f20] __x64_sys_read at ffffffff81583d1a
#10 [ffffbec20dad7f30] do_syscall_64 at ffffffff81f5f259
#11 [ffffbec20dad7f50] entry_SYSCALL_64_after_hwframe at ffffffff82000099
    RIP: 00000000004b4cab  RSP: 000000c0005fcff8  RFLAGS: 00000216
    RAX: ffffffffffffffda  RBX: 000000c00003d000  RCX: 00000000004b4cab
    RDX: 0000000000000200  RSI: 000000c0001e2e00  RDI: 0000000000000029
    RBP: 000000c0005fd048   R8: 0000000000000001   R9: 0000000000000002
    R10: 0000000000000200  R11: 0000000000000216  R12: ffffffffffffffff
    R13: 0000000000000008  R14: 0000000000000007  R15: 0000000000000010
    ORIG_RAX: 0000000000000000  CS: 0033  SS: 002b
crash> 
~~~

There are more than 24 thousand lxcfs threads I see in the vmcore. They all seem to be waiting on futex like this,

~~~
crash> bt
PID: 2395872  TASK: ffff9c1de04f6000  CPU: 35   COMMAND: "lxcfs"
 #0 [ffffbec3705efb18] __schedule at ffffffff81f6d0ed
 #1 [ffffbec3705efba0] schedule at ffffffff81f6d719
 #2 [ffffbec3705efbc0] futex_wait_queue_me at ffffffff81388b58
 #3 [ffffbec3705efbf8] futex_wait at ffffffff81389a05
 #4 [ffffbec3705efd18] do_futex at ffffffff8138b86a
 #5 [ffffbec3705efde8] __x64_sys_futex at ffffffff8138c32b
 #6 [ffffbec3705efe68] do_syscall_64 at ffffffff81f5f259
 #7 [ffffbec3705efeb0] __sys_socketpair at ffffffff81c8f333
 #8 [ffffbec3705eff10] __x64_sys_socketpair at ffffffff81c8f40e
 #9 [ffffbec3705eff20] do_syscall_64 at ffffffff81f5f269
#10 [ffffbec3705eff50] entry_SYSCALL_64_after_hwframe at ffffffff82000099
    RIP: 00007f40460dc5cb  RSP: 00007f069bcb28d8  RFLAGS: 00000246
    RAX: ffffffffffffffda  RBX: 0000000000000001  RCX: 00007f40460dc5cb
    RDX: 0000000000000002  RSI: 0000000000000080  RDI: 00007f4046236800
    RBP: 0000000000000001   R8: 0000000000000000   R9: 00007f069bcb2800
    R10: 0000000000000000  R11: 0000000000000246  R12: 0000000000000001
    R13: 00007f069bcb2d30  R14: 00007f069bcb2c90  R15: 0000000000000000
    ORIG_RAX: 00000000000000ca  CS: 0033  SS: 002b

crash> ps | grep lxcfs | wc -l                   
24387
crash> ps | grep lxd | wc -l  
78
crash> 
~~~

I am not sure which process is supposed to be the userspace helper for the fuse_simple_request() that all the kernel tasks are waiting on. I have some details of the vmcore noted here -  https://paste.ubuntu.com/p/qY26mRkpp9/

Can you help me understand if this is a libfuse deadlock, or something has gone wrong in userspace, and how I can understand which userspace process/pid I am supposed to debug further to see why its not responded?

**Comment by nkshirsagar** [comment] 2023-01-16 07:31
I'm dealing with an issue an Ubuntu user faces where an openstack management node (hosting several containers) running lxcfs ends up with a kernel hang with lots of lxcfs tasks in UN state leading to khungtaskd panicking the machine. The traces seen are like 

~~~
crash> bt
PID: 1177107  TASK: ffff9aee2f1da000  CPU: 7    COMMAND: "df"
 #0 [ffffb5b65e5e7a70] __schedule at ffffffffb536d0ed
 #1 [ffffb5b65e5e7af8] schedule at ffffffffb536d719
 #2 [ffffb5b65e5e7b18] request_wait_answer at ffffffffb4afd906
 #3 [ffffb5b65e5e7b78] fuse_simple_request at ffffffffb4b0005c
 #4 [ffffb5b65e5e7bb0] fuse_do_getattr at ffffffffb4b01087
 #5 [ffffb5b65e5e7cd8] fuse_getattr at ffffffffb4b02be9
 #6 [ffffb5b65e5e7d10] vfs_getattr_nosec at ffffffffb498920a
 #7 [ffffb5b65e5e7d20] vfs_getattr at ffffffffb4989267
 #8 [ffffb5b65e5e7d50] vfs_statx at ffffffffb4989309
 #9 [ffffb5b65e5e7da8] __do_sys_newstat at ffffffffb498989e
#10 [ffffb5b65e5e7e58] __x64_sys_newstat at ffffffffb49898f6
#11 [ffffb5b65e5e7e68] do_syscall_64 at ffffffffb535f259
#12 [ffffb5b65e5e7e88] exit_to_user_mode_prepare at ffffffffb476a1bc
#13 [ffffb5b65e5e7ec8] syscall_exit_to_user_mode at ffffffffb5363957
#14 [ffffb5b65e5e7ee0] do_syscall_64 at ffffffffb535f269
#15 [ffffb5b65e5e7f10] irqentry_exit_to_user_mode at ffffffffb53639e9
#16 [ffffb5b65e5e7f20] irqentry_exit at ffffffffb5363a1d
#17 [ffffb5b65e5e7f30] sysvec_apic_timer_interrupt at ffffffffb5362b6e
#18 [ffffb5b65e5e7f50] entry_SYSCALL_64_after_hwframe at ffffffffb5400099
    RIP: 00007f7004c274ba  RSP: 00007ffc14cdbcf8  RFLAGS: 00000246
    RAX: ffffffffffffffda  RBX: 000055be101148b0  RCX: 00007f7004c274ba
    RDX: 00007ffc14cdbd90  RSI: 00007ffc14cdbd90  RDI: 000055be10111f40
    RBP: 000055be10111ee0   R8: 0000000000000001   R9: 000000000000007c
    R10: ffffffffffffffff  R11: 0000000000000246  R12: 000055be10111e20
    R13: 000055be10111fa0  R14: 0000000010111e00  R15: 00007ffc14cdbd70
    ORIG_RAX: 0000000000000004  CS: 0033  SS: 002b
crash> 
~~~

I discussed this issue with @mihalicyn and even reproduced it once this way using a simple fuse filesystem (hello.c from libfuse examples but with a getattr that simply does a huge sleep() effectively making fuse daemon "unresponsive")

~~~
static int hello_getattr(const char *path, struct stat *stbuf)
{
int res = 0;
sleep(1000000);
return res;
}

We mount the fuse fs (with the shell in which we start the daemon added to a cgroup with a low pid limit), (reproducer folder is the new folder i created in the /sys/fs/cgroup) and then ran in it,

echo "+pids" > cgroup.subtree_control
echo pid_of_the_shell > cgroup.procs (echo $$)
echo 10000 | tee pids.max

Start the daemon,

root@z-rotomvm03:/sys/fs/cgroup/reproducer# /home/ubuntu/fuse_fs/hello -d -f /home/ubuntu/for_mount/
FUSE library version: 2.9.9
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 2, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.34
flags=0x33fffffb
max_readahead=0x00020000
INIT: 7.19
flags=0x00000011
max_readahead=0x00020000
max_write=0x00020000
max_background=0
congestion_threshold=0
unique: 2, success, outsize: 40

and then from another shell send more than that pids.max number of "stat" calls, like

for i in $(seq 15000); do echo $i; stat ../for_mount & done

We see "fuse: error creating thread: Resource temporarily unavailable" errors from the fuse daemon, especially if i mount 2 different fuse filesystems at the same time in different locations (presumably thats what the openstack mgmt server does, mounting lxcfs filesystems for each container?)

A df issued after it was hung a long time with tasks in S+ showed the traces - 
( https://paste.ubuntu.com/p/r6kYhXXdxJ/ ), somehow all the blocked tasks went to UN state after we issued the df. I am not sure if its related but it happened a few minutes after the df was issued, whereas it was hung without blocked UN tasks for 24 hours without the kernel threads going to UN unkillable state)

We still need to figure out why lxcfs is not responding, here we force our test fuse daemon to sleep to reproduce the UN blocked tasks in the kernel. (libfuse bug perhaps when pid max is hit?? But why the openstack mgmt server hit pid max all the time is still a question, it might be something mtail is doing, but thats just a suspicion at this point.)

We see more than 250k journal logs of
"fuse: error creating thread: Resource temporarily unavailable" in one day alone in the openstack mgmt server journal logs of the host - sosreport available if needed for analysis)

vmcores from the hung server (not my reproducer) shows a lot of mtail tasks in the kernel.. 1 vmcore had 25k+ lxcfs tasks.. 
lots of mtail (and apache) tasks are also seen..
crash> ps | grep mtail | wc -l
3361

another vmcore had 4202 such threads of lxcfs in the kernel at time of the panic.. (https://pastebin.canonical.com/p/yqVZYb4s4p/)

crash> ps | grep lxcfs | wc -l
4202
~~~

**Comment by mihalicyn** [comment] 2023-01-16 11:52
Thanks @nkshirsagar
Kernel crashdump that you've provided was really helpful. https://github.com/lxc/lxcfs/pull/579

**Comment by mihalicyn** [comment] 2023-09-29 10:09
I think we can close this as fixed.

cc @stgraber

**Closed** 2023-09-29 11:23 UTC
