### ISSUE TITLE
A segfault was found

### ISSUE THREAD

**Issue by ganker-z** [lxc/lxcfs#453] opened 2021-04-02 08:10 UTC
A segfault was found when i run lxcfs 4.0.7 with libfuse2.9.9,  the backtrace is as follows

**Comment by ganker-z** [comment] 2021-04-02 08:11
![image](https://user-images.githubusercontent.com/31061668/113396386-0c123d00-93ce-11eb-9e21-b2b05d0bca3d.png)

**Comment by ganker-z** [comment] 2021-04-02 08:12
![image](https://user-images.githubusercontent.com/31061668/113396432-1e8c7680-93ce-11eb-98d8-06db68f2ee86.png)

**Comment by stgraber** [comment] 2021-05-27 18:51
@brauner what would we need to track this one down?

**Comment by brauner** [comment] 2021-05-28 07:22
I have one wild guess but I need the output of `ldd` on the `lxcfs` binary and the `liblxcfs.so` libtool module, please.

**Comment by stgraber** [comment] 2021-05-28 13:47
@ganker-z if this is still an issue for you, can you provide that information?

**Comment by brauner** [comment] 2021-05-28 13:49
I would expect crashes like that when e.g. `lxcfs` is linked against fuse 2 and `liblxcfs` linked against fuse `3.

**Comment by ganker-z** [comment] 2021-05-31 02:44
<img width="392" alt="rBAoL2C0S_6Ab8CmAAB9ixKE2Pc628" src="https://user-images.githubusercontent.com/31061668/120132248-99baaf00-c1fc-11eb-8019-424f05501309.png">
The above pictrue is the ldd output of lxcfs and libfuse

**Comment by stgraber** [comment] 2021-05-31 04:48
The second `ldd` should be against `liblxcfs.so` not `libfuse.so`

**Comment by ganker-z** [comment] 2021-05-31 06:12
<img width="411" alt="rBAoL2C0fXGAFWodAABGJOhNxrk972" src="https://user-images.githubusercontent.com/31061668/120147933-085a3580-c21a-11eb-9dbe-cc02f64ae695.png">
ldd output of liblxcfs.so

**Comment by brauner** [comment] 2021-05-31 14:01
Ah, damn. I forgot that we don't link `liblxcfs.so` against fuse. @ganker-z, is it possible for you to get me the `liblxcfs.so` binary?

**Comment by ganker-z** [comment] 2021-06-01 01:54
[liblxcfs.zip](https://github.com/lxc/lxcfs/files/6572850/liblxcfs.zip)
liblxcfs.so binary file

**Comment by ganker-z** [comment] 2021-06-03 07:45
> Ah, damn. I forgot that we don't link `liblxcfs.so` against fuse. @ganker-z, is it possible for you to get me the `liblxcfs.so` binary?

Is there any progress?

**Comment by brauner** [comment] 2021-06-03 11:41
Do you have any access to the build flags used to build this version of `liblxcfs`? I need to find out what fuse version it was built with.

**Comment by brauner** [comment] 2021-06-03 11:44
This could also be a fuse bug tbh since we don't make use of double-linked lists in lxcfs.

**Comment by ganker-z** [comment] 2021-06-03 11:45
> Do you have any access to the build flags used to build this version of `liblxcfs`? I need to find out what fuse version it was built with.
I built it according to the method in the readme
yum install fuse fuse-lib fuse-devel
git clone git://github.com/lxc/lxcfs
cd lxcfs
./bootstrap.sh
./configure
make
make install

**Comment by brauner** [comment] 2021-06-03 13:33
Right, you built it yourself?

**Comment by brauner** [comment] 2021-06-03 13:35
Can you show me:
```
pkg-config --libs fuse
pkg-config --libs fuse3
```
please?

**Comment by ganker-z** [comment] 2021-06-04 01:25
> Can you show me:
> 
> ```
> pkg-config --libs fuse
> pkg-config --libs fuse3
> ```
> 
> please?

![NRerNjbL](https://user-images.githubusercontent.com/31061668/120731739-cb8e8700-c516-11eb-96ee-9080b1428ebb.png)

**Comment by ganker-z** [comment] 2021-06-04 01:26
![NRerNjbL](https://user-images.githubusercontent.com/31061668/120731809-ef51cd00-c516-11eb-9c9b-bf7f573a87f7.png)

**Comment by ganker-z** [comment] 2021-06-04 01:29
> Can you show me:
> 
> ```
> pkg-config --libs fuse
> pkg-config --libs fuse3
> ```
> 
> please?

<img width="321" alt="rBAoRmC5ggGAQmiFAABErZ-d4sM545" src="https://user-images.githubusercontent.com/31061668/120732157-6b4c1500-c517-11eb-88de-d939c8e9d4fb.png">

**Comment by ganker-z** [comment] 2021-06-04 01:59
> Right, you built it yourself?

yes

**Comment by ganker-z** [comment] 2021-06-04 02:08
> This could also be a fuse bug tbh since we don't make use of double-linked lists in lxcfs.

How to understand this sentence, is it double-linked libfuse by lxcfs?

**Comment by brauner** [comment] 2021-06-04 06:31
> > This could also be a fuse bug tbh since we don't make use of double-linked lists in lxcfs.
> 
> How to understand this sentence, is it double-linked libfuse by lxcfs?

No. The first picture you pasted indicates that a double-linked list data structure got corrupted. We don't use double-linked lists as a data structure in lxcfs but fuse does. So there is a chance that you version of fuse has a bug.

**Comment by ganker-z** [comment] 2021-06-30 08:32
This is the stack information at the time of the problem, exported through gdb
There are two kinds of stack information, one is abort and the other is segmentation
![image](https://user-images.githubusercontent.com/31061668/123928702-bb0be800-d9c0-11eb-8a22-a75a7d3028de.png)
![image](https://user-images.githubusercontent.com/31061668/123928773-c9f29a80-d9c0-11eb-9468-a306358e7a3a.png)

**Comment by ganker-z** [comment] 2021-06-30 08:34
> > > This could also be a fuse bug tbh since we don't make use of double-linked lists in lxcfs.
> > 
> > 
> > How to understand this sentence, is it double-linked libfuse by lxcfs?
> 
> No. The first picture you pasted indicates that a double-linked list data structure got corrupted. We don't use double-linked lists as a data structure in lxcfs but fuse does. So there is a chance that you version of fuse has a bug.
Please take a look at the above comment，thanks

**Comment by ganker-z** [comment] 2021-06-30 08:35
> > > This could also be a fuse bug tbh since we don't make use of double-linked lists in lxcfs.
> > 
> > 
> > How to understand this sentence, is it double-linked libfuse by lxcfs?
> 
> No. The first picture you pasted indicates that a double-linked list data structure got corrupted. We don't use double-linked lists as a data structure in lxcfs but fuse does. So there is a chance that you version of fuse has a bug.

Please take a look at the above comment，thanks

**Comment by mihalicyn** [comment] 2023-09-29 15:33
No movement with this since 2021. I think we can close it until next reproducer.

Most likely it was libfuse bug, not the LXCFS one.

cc @stgraber

**Closed** 2023-09-29 16:12 UTC
Labels: Incomplete
