### ISSUE TITLE
/proc/uptime suddenly reset

### ISSUE THREAD

**Issue by zerkms** [lxc/lxcfs#223] opened 2017-11-19 19:38 UTC
2 days ago in Saturday, November 18th, 2017 `/cat/proc` on all containers of one host has suddenly reset.

As of now it outputs

```
$ cat /proc/uptime 
144686.0 142649.0
```

The containers in fact have not been actually restarted and each of those runs the processes that have start time that matches the recent actual host restart (which happened last time at approximately November 8th, 11 days ago).

Host os: ubuntu 16.04
Versions of lxc/lxcfs/lxd

```
ii  liblxc1                            2.0.8-0ubuntu1~16.04.2                     amd64        Linux Containers userspace tools (library)
ii  lxc-common                         2.0.8-0ubuntu1~16.04.2                     amd64        Linux Containers userspace tools (common tools)
ii  lxcfs                              2.0.7-0ubuntu1~16.04.2                     amd64        FUSE based filesystem for LXC
ii  lxd                                2.0.10-0ubuntu1~16.04.2                    amd64        Container hypervisor based on LXC - daemon
ii  lxd-client                         2.0.10-0ubuntu1~16.04.2                    amd64        Container hypervisor based on LXC - client
```

**Comment by zerkms** [comment] 2017-11-20 20:15
And it just happened again - 
```
$ cat /proc/uptime 
423.0 423.0
```

On the same host the uptime for containers was reset, the containers has not been restared though.

**Comment by Blub** [comment] 2017-11-21 12:55
Not sure which versions were affected by this, but does the reset happen when you do
`# echo 1 > /proc/sys/vm/drop_caches` ?

**Comment by zerkms** [comment] 2017-11-21 18:58
After running it the containers `/proc/uptime` did not reset.

**Comment by consi** [comment] 2018-01-09 19:19
Today we got same issue in containers running on 
# lxcfs --version
2.0.7
and
# lxcfs --version
2.0.6

Uptime just randomly resets to 0 several times per day

**Comment by tomamplius** [comment] 2018-03-01 12:26
I have the same issue on 2 servers. But others servers with the same version have not the issue

lxcfs --version
2.0.6

**Comment by brauner** [comment] 2018-03-01 12:30
What about `2.0.8`?

**Comment by tomamplius** [comment] 2018-03-01 12:34
Currently any servers with this version (2.0.8) have this issue.

I need upgrade production server to know if the upgrade solve this issue.

**Comment by tomamplius** [comment] 2018-03-01 13:42
Upgrade done on one server. I will confirm in 2 or 3 days

**Comment by tomamplius** [comment] 2018-03-10 09:39
Done for me, since the 2.0.8 upgrade.

**Comment by brauner** [comment] 2018-03-10 14:32
On Sat, Mar 10, 2018 at 09:39:39AM +0000, tomamplius wrote:
> Done for me, since the 2.0.8 upgrade. 

"Done for me" as in "not reproducible anymore"?

Christian

**Comment by tomamplius** [comment] 2018-03-10 22:09
sorry, yes

**Comment by brauner** [comment] 2018-06-15 11:15
Ok, closing then.

**Closed by brauner** 2018-06-15 11:15 UTC
