### ISSUE TITLE
Guest able to view its host DRBD process

### ISSUE THREAD

**Issue by AhmadFazliIsmail** [lxc/lxcfs#246] opened 2018-06-23 00:36 UTC
Hello,

I have installed lxcfs-3.0.1 in CentOS 7 (kernel 4.4.138-1.el7.elrepo.x86_64) and run LXC guests using libvirt-lxc (libvirt-daemon-driver-lxc-3.9.0-14.el7_5.5.x86_64). The images are stored in an LVM partition which uses DRBD (drbd90-utils-9.3.1-1.el7.elrepo.x86_64). Everything is working fine, but the `/proc/drbd` existed in the guests. I can execute `cat /proc/drbd` in the guests to monitor the DRBD status of the host! I think that only the host is permitted to monitor the DRBD status and not the guests.

Thank you.

**Comment by brauner** [comment] 2018-06-27 12:22
On Fri, Jun 22, 2018 at 05:36:04PM -0700, Konsortium ICT Pantai Timur wrote:
> Hello,
> 
> I have installed lxcfs-3.0.1 in CentOS 7 (kernel
> 4.4.138-1.el7.elrepo.x86_64) and run LXC guests using libvirt-lxc
> (libvirt-daemon-driver-lxc-3.9.0-14.el7_5.5.x86_64). The images are
> stored in an LVM partition which uses DRBD
> (drbd90-utils-9.3.1-1.el7.elrepo.x86_64). Everything is working fine,
> but the `/proc/drbd` existed in the guests. I can execute `cat
> /proc/drbd` in the guests to monitor the DRBD status of the host! I
> think that only the host is permitted to monitor the DRBD status and
> not the guests.

That's unrelated to LXCFS in general. To fix this you'd need to
implement /proc/drbd virtualization in LXCFS but that's a very specific
use case and unlikely to be merged.

**Comment by AhmadFazliIsmail** [comment] 2018-06-27 12:50
Hi @brauner ,

I don't think so since LXCFS mentioned

LXCFS is a small FUSE filesystem written with the **intention of making Linux containers feel more like a virtual machine**. It started as a side-project of LXC but is useable by any runtime.

In my opinion DRBD process is part of the files in `procfs` and is possible to be hide from the guests same as `uptime`.

Thank you.

**Comment by brauner** [comment] 2018-07-31 16:06
Right, but this is a very specific file that won't be used by a lot of users so I don't know how valuable it would be to mock that file actually. At least we don't have any intentions on adding this to the virtualized files at the moment. The problem is to maintain a good compromise between focus, performance, and features.

**Closed by brauner** 2018-07-31 16:06 UTC

**Comment by hallyn** [comment] 2018-08-10 14:43
Quoting Konsortium ICT Pantai Timur (notifications@github.com):
> Hello,
> 
> I have installed lxcfs-3.0.1 in CentOS 7 (kernel 4.4.138-1.el7.elrepo.x86_64) and run LXC guests using libvirt-lxc (libvirt-daemon-driver-lxc-3.9.0-14.el7_5.5.x86_64). The images are stored in an LVM partition which uses DRBD (drbd90-utils-9.3.1-1.el7.elrepo.x86_64). Everything is working fine, but the `/proc/drbd` existed in the guests. I can execute `cat /proc/drbd` in the guests to monitor the DRBD status of the host! I think that only the host is permitted to monitor the DRBD status and not the guests.

Hm - this actually sounds like a kernel bug that should be fixed
upstream.
