### ISSUE TITLE
/proc/diskstats does not contain the drive LXD is on

### ISSUE THREAD

**Issue by C0rn3j** [lxc/lxcfs#432] opened 2020-09-09 09:24 UTC
Using 4.0.3 LXD from snap.

As discussed in https://github.com/lxc/lxcfs/issues/148, which is now closed as the original issue was diskstats not displaying ANYTHING, the filtering is still too aggressive.

In this case, I'd expect the nvme4n1 to show up in diskstats since the container uses it due to `/var/snap/lxd/common/lxd` residing on that drive

Instead the container ONLY sees the drive host / is on.

Host:
```
[130] # lsblk        
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
loop0         7:0    0  55.3M  1 loop  /snap/core18/1885
loop1         7:1    0  29.9M  1 loop  /snap/snapd/8790
loop2         7:2    0  70.6M  1 loop  /snap/lxd/16922
sda           8:0    0   7.3T  0 disk  
└─sda1        8:1    0   7.3T  0 part  /glusterfs
sdb           8:16   0 446.6G  0 disk  
├─sdb1        8:17   0   953M  0 part  /boot/efi
├─sdb2        8:18   0  29.8G  0 part  /
└─sdb3        8:19   0  29.8G  0 part  [SWAP]
nvme1n1     259:0    0   1.5T  0 disk  
└─nvme1n1p1 259:4    0   1.5T  0 part  
  └─md0       9:0    0   1.5T  0 raid1 /mnt/xfs1
nvme0n1     259:1    0   1.5T  0 disk  
└─nvme0n1p1 259:3    0   1.5T  0 part  
  └─md0       9:0    0   1.5T  0 raid1 /mnt/xfs1
nvme2n1     259:2    0   1.5T  0 disk  
└─nvme2n1p1 259:5    0   1.5T  0 part  
  └─md1       9:1    0   1.5T  0 raid1 /mnt/xfs2
nvme3n1     259:6    0   1.5T  0 disk  
└─nvme3n1p1 259:7    0   1.5T  0 part  
  └─md1       9:1    0   1.5T  0 raid1 /mnt/xfs2
nvme5n1     259:8    0   1.5T  0 disk  
├─nvme5n1p1 259:12   0     1T  0 part  
└─nvme5n1p2 259:13   0 466.4G  0 part  
  └─md127     9:127  0 466.3G  0 raid1 /mnt/xfs3
nvme4n1     259:9    0   1.5T  0 disk  
├─nvme4n1p1 259:10   0     1T  0 part  /var/snap/lxd/common/lxd
└─nvme4n1p2 259:11   0 466.4G  0 part  
  └─md127     9:127  0 466.3G  0 raid1 /mnt/xfs3
```

Container:
```
# cat /proc/diskstats 
8       16 sdb 4 0 32 0 0 0 0 0 0 0 0
```

The workaround is to `umount /proc/diskstats`

**Comment by stgraber** [comment] 2020-09-09 16:11
@brauner can you take a look at this?

**Comment by brauner** [comment] 2020-09-10 10:08
LXCFS won't display a drive in diskstats when there's no non-0 values in the corresponding blkio cgroup files. That's the only way we can reasonably filter right now. So can you show the contents of the `blkio.io_serviced_recursive` file in the containers' blkio cgroup, please?

**Comment by C0rn3j** [comment] 2020-09-10 10:18
If I understood completely, you want `/var/lib/lxcfs/cgroup/blkio/lxc.payload.censoredcontainername/blkio.io_serviced_recursive`, displayed from within the container?
```
# cat /var/lib/lxcfs/cgroup/blkio/lxc.payload.censoredcontainername/blkio.io_serviced_recursive
Total 0
```

**Comment by brauner** [comment] 2020-09-10 10:52
Yes, thanks!
You can see the problem in the file. You can check in what files the blkio cgroup the corresponding device you want to have information on is present. If it isn't like in this case LXCFS can't virtualize because there's no cgroup information for the device it can rely on.

Are you using `zfs` at all for your containers? If so then there's the slight problem that `zfs` doesn't use the page cache and so blkio cgroup accounting is basically meaningless for `zfs` in the first place.

**Comment by C0rn3j** [comment] 2020-09-10 11:04
No, host `/` is ext4, and LXD mountpoint is btrfs
```
/dev/sdb2 on / type ext4 (rw,relatime,errors=remount-ro,stripe=64,data=ordered)
/dev/nvme4n1p1 on /var/snap/lxd/common/lxd type btrfs (rw,relatime,compress=lzo,ssd,space_cache,user_subvol_rm_allowed,subvolid=5,subvol=/)
```

**Comment by brauner** [comment] 2020-09-10 12:45
Fwiw, what io scheduler are you using for the nvme?
```
cat /sys/block/nvme4n1/queue/scheduler
```

The problem is again, that the file is empty and so LXCFS can't do any virtualization for you. :/

**Comment by C0rn3j** [comment] 2020-09-10 12:57
Host:
```
[0] # cat /sys/block/nvme4n1/queue/scheduler
[none] 
```

From a quick search there seem to be no schedulers available because
```
None is displayed because no scheduler is in use.
SSDs using the NVMe protocol instead of SATA bypass the traditional I/O scheduler.
```

**Comment by brauner** [comment] 2020-09-10 13:04
> Host:
> 
> ```
> [0] # cat /sys/block/nvme4n1/queue/scheduler
> [none] 
> ```
> 
> From a quick search there seem to be no schedulers available because
> 
> ```
> None is displayed because no scheduler is in use.
> SSDs using the NVMe protocol instead of SATA bypass the traditional I/O scheduler.
> ```
> 
> > the file is empty and so LXCFS can't do any virtualization for you
> 
> My use case is that there need to be IO metrics available for the container on the drive the container is running on, is there a more clean workaround than umounting entire /proc/diskstats or is that currently the cleanest way?

Yeah, I know that. Some `nvme` devices let you use one though
```
brauner@wittgenstein|~
> cat /sys/block/nvme0n1/queue/scheduler
[none] mq-deadline 
```

In any case, I don't think there's currently a better way than to unmount it, I think.

**Comment by brauner** [comment] 2020-09-14 14:22
Closing this for now but please re-open if you come up with a clever trick to handle this better! :)

**Closed by brauner** 2020-09-14 14:22 UTC
Labels: Incomplete
