### ISSUE TITLE
lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache.

### ISSUE THREAD

**Issue by jcarnus** [lxc/lxcfs#176] opened 2017-02-24 12:22 UTC
Hi,
I find this log very often in my syslog log on a machine that host some LXC containers.
This seems due to some uptime command or ps-aux command that are run from the lxc container

**Comment by brauner** [comment] 2017-02-24 13:05
Could you please provide a minimal set of information:

- distribution used
- kernel version
- lxcfs version

**Comment by jcarnus** [comment] 2017-02-24 13:25
Yes
It's a proxmox 4.4 under Jessie.

Kernel is 4.4.40 version 

Lxcfs is at 2.0.6


Jérémy Carnus
________________________________
De: Christian Brauner <notifications@github.com>
Envoyé: 24 févr. 2017 8:05 AM
À: lxc/lxcfs
Cc: jcarnus; Author
Objet: Re: [lxc/lxcfs] lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache. (#176)

Could you please provide a minimal set of information:

distribution used
kernel version
lxcfs version

**Comment by jcarnus** [comment] 2017-03-11 11:15
Hello,
No news for this ?
Thanks

**Comment by brauner** [comment] 2017-03-11 11:16
Do you have a reproducer for this issue?

**Comment by jcarnus** [comment] 2017-03-11 11:26
I noticed that a ps aux command running periodically (each minute) in a lxc-container will finish by trigerring this error on the host. I dont know if this can help you

**Comment by brauner** [comment] 2017-03-11 12:22
@jcarnus, how many cores does this system have?

**Comment by brauner** [comment] 2017-03-11 12:24
@jcarnus, please paste the output of `cat /proc/stat`.

**Comment by jcarnus** [comment] 2017-03-11 12:29
cpu  20020868 8989724 8010931 464349766 15263497 0 177838 0 93516 0
cpu0 4477073 1839392 2082654 118587904 1884910 0 153962 0 17746 0
cpu1 5126757 2277256 1989894 116434466 3426212 0 10219 0 23917 0
cpu2 5241212 2444142 1974203 114753987 4837268 0 7028 0 26205 0
cpu3 5175824 2428933 1964178 114573408 5115107 0 6627 0 25647 0
intr 1902660831 17 2 0 0 0 0 0 0 1 3 0 0 4 0 0 0 29 0 0 0 0 0 0 33 0 0 0 0 0 0 0 68927974 87565552 13 19 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 4706417564
btime 1487936548
processes 19006114
procs_running 2
procs_blocked 0
softirq 1255381787 6 385691062 818350 145504471 83452947 0 59361 203772428 0 436083162

Jérémy Carnus
________________________________
De: Christian Brauner <notifications@github.com>
Envoyé: 11 mars 2017 7:24 AM
À: lxc/lxcfs
Cc: jcarnus; Mention 
Objet: Re: [lxc/lxcfs] lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache. (#176)

@jcarnus, please paste the output of cat /proc/stat.

**Comment by brauner** [comment] 2017-03-11 12:45
Thanks. Can you please show the same information from inside the container?

**Comment by jcarnus** [comment] 2017-03-11 13:36
cpu  20097605 9018144 8035562 465776502 15305596 0 178250 0 93515
cpu0 4494542 1842902 2088862 118955188 1889431 0 154321 0 17746 0
cpu1 5147622 2283558 1996062 116791977 3435238 0 10243 0 23917 0
cpu2 5260953 2454202 1980336 115105130 4849978 0 7045 0 26205 0
cpu3 5194488 2437482 1970302 114924207 5130949 0 6641 0 25647 0
intr 1908388837 17 2 0 0 0 0 0 0 1 3 0 0 4 0 0 0 29 0 0 0 0 0 0 33 0 0 0 0 0 0 0 69036188 87835989 13 19 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 4720764640
btime 1487936548
processes 19062892
procs_running 1
procs_blocked 0
softirq 1258993250 6 386869171 819963 145787230 83710099 0 59361 204378797 0 437368623

Jérémy Carnus
________________________________
De: Christian Brauner <notifications@github.com>
Envoyé: 11 mars 2017 7:45 AM
À: lxc/lxcfs
Cc: jcarnus; Mention 
Objet: Re: [lxc/lxcfs] lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache. (#176)

Thanks. Can you please show the same information from inside the container?

**Comment by brauner** [comment] 2017-03-11 13:58
Ah, cool there's another bug, `guest nice` is missing.

**Comment by jcarnus** [comment] 2017-03-11 14:41
I didn't get. Did you find another bug or is it linked to another bug? Did you want me to execute something?

Thanks

Jérémy Carnus
________________________________
De: Christian Brauner <notifications@github.com>
Envoyé: 11 mars 2017 8:58 AM
À: lxc/lxcfs
Cc: jcarnus; Mention 
Objet: Re: [lxc/lxcfs] lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache. (#176)

Ah, cool there's another bug, guest nice is missing.

**Comment by brauner** [comment] 2017-03-11 14:49
Nah, thanks you don't need to provide additional information for now. This is linked to another bug.

**Comment by brauner** [comment] 2017-03-11 15:53
So one explanation is that there is a time-of-check time-of-use race. The file info that fuse provides, especially the file size, might change by the time when we read from the file itself and the discrepancy might be big enough (even with additional 256 bytes) to cause truncated writes.

**Comment by jcarnus** [comment] 2017-03-11 15:58
But why the file size will change. It's almost constant?

Jérémy Carnus
________________________________
De: Christian Brauner <notifications@github.com>
Envoyé: 11 mars 2017 10:53 AM
À: lxc/lxcfs
Cc: jcarnus; Mention 
Objet: Re: [lxc/lxcfs] lxcfs[2260]: bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache. (#176)

So one explanation is that there is a time-of-check time-of-use race. The file info that fuse provides, especially the file size, might change by the time when we read from the file itself and the discrepancy might be big enough (even with additional 256 bytes) to cause truncated writes.

**Comment by brauner** [comment] 2017-03-11 16:04
If there's one byte too many it should be enough. There's also the fact that only `proc_stat_read()` is fully using `BUF_RESERVE_SIZE` so it doesn't actually benefit from the additional memory assigned to it. I think I'll tweak this a little by increasing `BUF_RESERVE_SIZE` and having `CPUALL_MAX_SIZE` only use a portion of it.

**Comment by brauner** [comment] 2017-03-11 16:10
Hm, I wonder if this actually could be caused by the unaccounted guest nice...

**Comment by onlime** [comment] 2018-02-21 23:39
did this yet make it into lxcfs 2.0.8? I am still experiencing the following in avg twice a second on Proxmox VE 5.1 host with a rather big LXC container:

```
lxcfs[4845]: bindings.c: 3664: proc_stat_read: Internal error: truncated write to cache.
```

**Comment by hallyn** [comment] 2018-02-25 04:44
Yes, it is in 2.0.8, so if it didn't solve it for you, please re-open, or perhaps open a new bug with a fresh set of data.

**Comment by lastb0isct** [comment] 2018-02-26 01:28
This is constantly spamming mine as well...once per second.

**Comment by hallyn** [comment] 2018-02-26 20:30
@lastb0isct exactly which lxcfs version?

**Comment by lastb0isct** [comment] 2018-02-26 20:43
Running proxmox version 5.1-41, lxcfs is 2.0.8

**Comment by marvinwankersteen** [comment] 2018-06-04 14:39
Same Problem. The server sometimes randomly reboots and then did not find the disks.

```
Debian 8.10
Linux proxmox 4.4.40-1-pve #1 SMP PVE 4.4.40-82
lxc-pve                        2.0.7-4
lxcfs                          2.0.6-pve1
proxmox-ve                     4.4-108
```

No error in logs, except `bindings.c: 3523: proc_stat_read: Internal error: truncated write to cache.`

I have to turn off the server and then start again. If I just reboot the server it will not boot.

**Comment by tobi-the-fraggel** [comment] 2018-12-12 23:55
I am also getting this on Ubuntu16.04 with lxcfs 2.0.8
lxc version 2.0.11
kernel 4.9.135

Just today I see 1829 of these messages in syslog
I am also having a containerized service which recently started to hang up in uniterruptible sleep quite often. It wasn't doing this up to a few months ago. I always wondered what is causing it and now suspect this error being related.

**Comment by nulluserid** [comment] 2018-12-31 22:43
Seeing this too on Ubuntu 18.04
LXC Version 3.0.3
LXCFS Version 3.0.3

**Comment by tobi-the-fraggel** [comment] 2019-03-26 22:33
Still getting this error. Just like 4 months ago and nothing happens. If you guys have an idea about the underlying problem, it loos like it, could you at least provide us with a workaround? That would be appreciated so much! :*

**Comment by garymol** [comment] 2019-07-23 15:22
Just to add to this report, I am seeing this error frequently as well, but inconsistently across 5 different LXD hosts.  One LXD host had 49M errors over 4 weeks, the others had less than 200:

Distro: Centos 7.6.1810
Kernel: 4.4.166-1.el7.elrepo.x86_64
LXD: 3.14

**Comment by nulluserid** [comment] 2019-09-09 22:33
Update on my end, ended up going to. 19.04 with LXC 3.0.4, and the error still occurs.

**Comment by inoex135** [comment] 2020-02-17 04:12
is there any solution about this? any workaround, I googled it, but found nothing.

**Comment by brauner** [comment] 2020-03-03 14:09
LXCFS master has been reworked significantly and I can't reproduce this bug. If someone still can, please re-open.

**Closed by brauner** 2020-03-03 14:09 UTC
Labels: Bug

**Comment by Tokukarin** [comment] 2023-01-29 03:44
![image](https://user-images.githubusercontent.com/50606374/215303610-1f776608-2bfc-4cbe-8220-a3b3ddd18816.png)
Disclaimer, no idea If this is related or what is the reason for it.
I stumbled across this to find out what it could be. Maybe it's related.

**Comment by 3gksoftware** [comment] 2023-04-20 07:17
Bug still present, any fix for this coming soon ?

**Comment by Oriann** [comment] 2023-08-11 14:24
Error occuring on my host too, is there a solution ?

![image](https://github.com/lxc/lxcfs/assets/11374526/a595abaa-a680-49d5-9f1b-8d554606c8a4)

**Comment by 3gksoftware** [comment] 2023-08-12 09:56
I found a workaround that is working on proxmox : 

Bulk stop all vms  then systemctl restart lxcfs then bulk restart all vms.

all steps are mandatory. 

Now everything is fine until next server reboot (in that case you need to do the procedure again)

**Comment by SlashGIP** [comment] 2023-08-31 11:59
.Solution for me

https://forum.proxmox.com/threads/lxcfs-and-load-average.63254/

**Comment by Oriann** [comment] 2023-08-31 12:15
> .Solution for me
> 
> https://forum.proxmox.com/threads/lxcfs-and-load-average.63254/

So editing lxcfs.service with this conf `ExecStart=/usr/bin/lxcfs -l --enable-cfs --enable-pidfd /var/lib/lxcfs` worked for u ?

**Comment by GrumpyMeow** [comment] 2024-05-30 11:54
I think this issue might re-appear. I currently have this issue on:
* 6.8.4-3-pve
* Debian version: 12.5
* ProxmoxVE v8.2.2
