### ISSUE TITLE
host shutdown/reboot hangs

### ISSUE THREAD

**Issue by aarnaud** [lxc/lxcfs#92] opened 2016-03-16 23:53 UTC
With ubuntu trusty 14.04.4 when i installed lxcfs from ppa lxd-stable, i can't reboot or power off the host. 
I need to press the power button on physical machine or to send an ACPI signal on VirtualBox.

**lxcfs version tried** : 2.0.0.rc5
**lxc version tried** : 2.0.0rc10
**kernel version tried**: 4.2.0-27-generic and 4.4.0-13-generic

I don't show any logs in `syslog`, `kernel.log`, `dmesg`, `lxcfs.log` when i run `sudo reboot`

To reproduce on a fresh ubuntu 14.04.4:

```bash
sudo apt-get -y install software-properties-common
sudo apt-add-repository -y ppa:ubuntu-lxc/lxd-stable
sudo apt-get update
sudo apt-get -y install lxc --no-install-recommends
sudo reboot # OK
sudo reboot # OK
sudo reboot # OK
sudo apt-get -y install lxcfs
sudo reboot # OK
sudo reboot # hangs, execution finish but no reboot
# After manual reboot
sudo reboot # hangs, execution finish but no reboot
# After manual reboot
sudo reboot # hangs, execution finish but no reboot
# After manuel reboot
sudo apt-get -y purge lxcfs
sudo reboot # OK
sudo reboot # OK
sudo reboot # OK
````

You can change installation order between lxc and lxcfs, same result. 

I remain available for any other test.
If necessary, I can export my virtualbox machine.

Thanks,
Anthony

**Comment by hallyn** [comment] 2016-03-17 07:35
Thanks, I can reproduce this.  Particularly odd that 3.13 kernel
didn't do this.  (iirc)

Running lxcfs by hand does not have this effect.  Commenting
out the pre-stop does not help.  lxcfs is not being started in
cgroups by upstart.

Maybe it has to do with the ptracing of lxcfs by upstart?

**Comment by aarnaud** [comment] 2016-03-18 13:46
Do you known when this bug will be fix ? 
With the next release ?

Thanks very much

**Comment by hallyn** [comment] 2016-03-20 21:06
I was wrong about 3.13 not doing it, that was spurious.  The problem is in the start on condition, which is blocking lxc from being marked as fully started.

i will post a fix on tomorrow.

**Closed** 2016-03-21 16:04 UTC
