### ISSUE TITLE
uptime shows as 0 and errors with bad data in /proc/uptime centos 7 when running top command

### ISSUE THREAD

**Issue by tomponline** [lxc/lxcfs#191] opened 2017-06-18 10:43 UTC
I am running lxcfs stable-2.0 branch commit https://github.com/lxc/lxcfs/commit/5dcba7d16daadc45e2e25cca3eef8caa5bbe05c4 compiled on CentOS 7 x86_64 bit.

When running top command in a centos 7 container, the uptime shows as "0" and outputs the following every refresh:

bad data in /proc/uptime

Output of /proc/uptime

```
[root@el7build01 ~]# cat /proc/uptime
629.00 397.00
```

CentOs 6 containers running on the same version of lxcfs dont have this issue,

output of /proc/uptime

```
[root@el6build01 ~]# cat /proc/uptime 
655.00 654.00
```

Kernel version:

Linux vz01 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tomponline** [comment] 2017-06-18 10:44
Output of a centos 7 hardware node of /proc/uptime if it helps

```
[root@vz01 ~]# cat /proc/uptime 
238820.30 469008.44
```

**Comment by tomponline** [comment] 2017-06-18 11:11
Not sure if related. but on the host systemctl status lxcfs shows

```
Jun 18 11:07:59 vz01.webisp.uk lxcfs[26820]: bindings.c: 3868: proc_uptime_read: failed to write to cache
Jun 18 11:07:59 vz01.webisp.uk lxcfs[26820]: bindings.c: 3868: proc_uptime_read: failed to write to cache
Jun 18 11:08:10 vz01.webisp.uk lxcfs[26820]: bindings.c: 3868: proc_uptime_read: failed to write to cache
Jun 18 11:08:10 vz01.webisp.uk lxcfs[26820]: bindings.c: 3868: proc_uptime_read: failed to write to cache
```

**Comment by tomponline** [comment] 2017-06-18 11:22
I've tracked the issue back to this commit https://github.com/lxc/lxcfs/commit/e48e16dc588e1a7718453f06b0f7228d13cd2c84

**Comment by brauner** [comment] 2017-06-18 11:24
Can you please show the output of `findmnt`?

**Comment by tomponline** [comment] 2017-06-18 11:26
This is the output when running findmnt inside el7 container with lxcfs https://github.com/lxc/lxcfs/commit/cb08328701fbfba05412923fa9c9b56534030e9d which is working fine

[rpmbuild@el7build01 lxcfs]$ findmnt
TARGET                                  SOURCE                          FSTYPE     OPTIONS
/                                       /dev/VolGroup00/el7build01      ext4       rw,relatime,seclabel,stripe=128,data=ordered
├─/run                                  tmpfs                           tmpfs      rw,nosuid,nodev,seclabel,mode=755
│ └─/run/user/1000                      tmpfs                           tmpfs      rw,nosuid,nodev,relatime,seclabel,size=104860k,mode=700,uid=1000,gid=1000
├─/dev                                  none                            tmpfs      rw,relatime,seclabel,size=492k,mode=755
│ ├─/dev/pts                            devpts                          devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/ptmx                           devpts[/ptmx]                   devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/lxc/tty1                       devpts[/0]                      devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/lxc/tty2                       devpts[/1]                      devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/lxc/tty3                       devpts[/2]                      devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/lxc/tty4                       devpts[/3]                      devpts     rw,relatime,seclabel,gid=5,mode=620,ptmxmode=666
│ ├─/dev/shm                            tmpfs                           tmpfs      rw,nosuid,nodev,seclabel
│ ├─/dev/lxc/console                    devpts[/2]                      devpts     rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000
│ ├─/dev/hugepages                      hugetlbfs                       hugetlbfs  rw,relatime,seclabel
│ └─/dev/mqueue                         mqueue                          mqueue     rw,relatime,seclabel
├─/proc                                 proc                            proc       rw,nosuid,nodev,noexec,relatime
│ ├─/proc/sys                           proc[/sys]                      proc       ro,nosuid,nodev,noexec,relatime
│ │ └─/proc/sys/net                     proc[/sys/net]                  proc       rw,nosuid,nodev,noexec,relatime
│ ├─/proc/sysrq-trigger                 proc[/sysrq-trigger]            proc       ro,nosuid,nodev,noexec,relatime
│ ├─/proc/cpuinfo                       lxcfs[/proc/cpuinfo]            fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/diskstats                     lxcfs[/proc/diskstats]          fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/meminfo                       lxcfs[/proc/meminfo]            fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/stat                          lxcfs[/proc/stat]               fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ ├─/proc/swaps                         lxcfs[/proc/swaps]              fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
│ └─/proc/uptime                        lxcfs[/proc/uptime]             fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
└─/sys                                  sysfs                           sysfs      rw,nosuid,nodev,noexec,relatime,seclabel
  └─/sys                                sysfs                           sysfs      ro,nosuid,nodev,noexec,relatime,seclabel
    ├─/sys/devices/virtual/net          sysfs                           sysfs      rw,relatime,seclabel
    │ └─/sys/devices/virtual/net        sysfs[/devices/virtual/net]     sysfs      rw,nosuid,nodev,noexec,relatime,seclabel
    ├─/sys/fs/fuse/connections          fusectl                         fusectl    rw,relatime
    └─/sys/fs/cgroup                    cgroup_root                     tmpfs      ro,nosuid,nodev,noexec,seclabel,size=10240k,mode=755
      ├─/sys/fs/cgroup/net_cls,net_prio cgroup                          cgroup     rw,nosuid,nodev,noexec,relatime,net_prio,net_cls
      ├─/sys/fs/cgroup/cpu,cpuacct      cgroup                          cgroup     rw,nosuid,nodev,noexec,relatime,cpuacct,cpu
      ├─/sys/fs/cgroup/blkio            lxcfs[/cgroup/blkio]            fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/cpuacct,cpu      lxcfs[/cgroup/cpuacct,cpu]      fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/cpuset           lxcfs[/cgroup/cpuset]           fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/devices          lxcfs[/cgroup/devices]          fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/freezer          lxcfs[/cgroup/freezer]          fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/hugetlb          lxcfs[/cgroup/hugetlb]          fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/memory           lxcfs[/cgroup/memory]           fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/systemd          lxcfs[/cgroup/name=systemd]     fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/net_prio,net_cls lxcfs[/cgroup/net_prio,net_cls] fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      ├─/sys/fs/cgroup/perf_event       lxcfs[/cgroup/perf_event]       fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
      └─/sys/fs/cgroup/pids             lxcfs[/cgroup/pids]             fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other

**Comment by tomponline** [comment] 2017-06-18 11:27
And on the hardware node:

```
[root@vz01 ~]# findmnt
TARGET                                SOURCE                        FSTYPE     OPTIONS
/                                     /dev/sda2                     ext4       rw,relatime,seclabel,data=ordered
├─/sys                                sysfs                         sysfs      rw,nosuid,nodev,noexec,relatime,seclabel
│ ├─/sys/kernel/security              securityfs                    securityfs rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/cgroup                    tmpfs                         tmpfs      ro,nosuid,nodev,noexec,seclabel,mode=755
│ │ ├─/sys/fs/cgroup/systemd          cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd
│ │ ├─/sys/fs/cgroup/hugetlb          cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,hugetlb
│ │ ├─/sys/fs/cgroup/net_cls,net_prio cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,net_prio,net_cls
│ │ ├─/sys/fs/cgroup/memory           cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,memory
│ │ ├─/sys/fs/cgroup/perf_event       cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,perf_event
│ │ ├─/sys/fs/cgroup/pids             cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,pids
│ │ ├─/sys/fs/cgroup/cpuset           cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,cpuset
│ │ ├─/sys/fs/cgroup/blkio            cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,blkio
│ │ ├─/sys/fs/cgroup/cpu,cpuacct      cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,cpuacct,cpu
│ │ ├─/sys/fs/cgroup/devices          cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,devices
│ │ └─/sys/fs/cgroup/freezer          cgroup                        cgroup     rw,nosuid,nodev,noexec,relatime,freezer
│ ├─/sys/fs/pstore                    pstore                        pstore     rw,nosuid,nodev,noexec,relatime
│ ├─/sys/fs/selinux                   selinuxfs                     selinuxfs  rw,relatime
│ ├─/sys/kernel/debug                 debugfs                       debugfs    rw,relatime
│ ├─/sys/kernel/config                configfs                      configfs   rw,relatime
│ └─/sys/fs/fuse/connections          fusectl                       fusectl    rw,relatime
├─/proc                               proc                          proc       rw,nosuid,nodev,noexec,relatime
│ └─/proc/sys/fs/binfmt_misc          systemd-1                     autofs     rw,relatime,fd=30,pgrp=1,timeout=300,minproto=5,maxproto=5,direct
├─/dev                                devtmpfs                      devtmpfs   rw,nosuid,seclabel,size=1892588k,nr_inodes=473147,mode=755
│ ├─/dev/shm                          tmpfs                         tmpfs      rw,nosuid,nodev,seclabel
│ ├─/dev/pts                          devpts                        devpts     rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000
│ ├─/dev/hugepages                    hugetlbfs                     hugetlbfs  rw,relatime,seclabel
│ └─/dev/mqueue                       mqueue                        mqueue     rw,relatime,seclabel
├─/run                                tmpfs                         tmpfs      rw,nosuid,nodev,seclabel,mode=755
│ └─/run/user/0                       tmpfs                         tmpfs      rw,nosuid,nodev,relatime,seclabel,size=380452k,mode=700
├─/boot                               /dev/sda1                     ext4       rw,relatime,seclabel,stripe=4,data=ordered
├─/vz/backup                          /dev/mapper/VolGroup00-backup ext4       rw,noatime,seclabel,stripe=128,data=ordered
└─/var/lib/lxcfs                      lxcfs                         fuse.lxcfs rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other
```

**Comment by brauner** [comment] 2017-06-18 11:30
Oh, ok `LXCFS 2.0.7` doesn't include https://github.com/lxc/lxcfs/commit/cb08328701fbfba05412923fa9c9b56534030e9d . Ok, I just want to understand why this is happening, can you please show me the output of:
```
ls -al /var/lib/lxcfs/proc
ls -al /var/lib/lxcfs/cgroup
cat /proc/self/cgroup
```

**Comment by tomponline** [comment] 2017-06-18 11:35
@brauner sorry ive confused the matter a bit. I was running master (not stable-2.0 or 2.0.7) when I noticed this issue. I'm not running 2.0.7 because of the stability issues when shutting down reported here https://github.com/lxc/lxcfs/issues/185.

However I was running master from 21 days ago, which means I had pulled in these 2 commits:

https://github.com/lxc/lxcfs/commit/0ecddf023a4caf8e8d2fe7e9125d777a06c5ec12
https://github.com/lxc/lxcfs/commit/9e7f9bc5abb0bd32fc88012ef9d1917011458fe1

So i tried switching to latest master which includes the commits in the last 6 days too, and it didn't fix it.

So I switched back to https://github.com/lxc/lxcfs/commit/e48e16dc588e1a7718453f06b0f7228d13cd2c84 before the uptime related commits and this has fixed it.

I'll switch back to master and get the output of those commands for you.

**Comment by tomponline** [comment] 2017-06-18 11:36
On commit https://github.com/lxc/lxcfs/commit/e48e16dc588e1a7718453f06b0f7228d13cd2c84 on hardware node:

```
[root@vz01 ~]# ls -al /var/lib/lxcfs/proc
total 0
dr-xr-xr-x. 2 root root 0 Jun 18 11:35 .
drwxr-xr-x. 2 root root 0 Jun 18 11:35 ..
-r--r--r--. 1 root root 0 Jun 18 11:35 cpuinfo
-r--r--r--. 1 root root 0 Jun 18 11:35 diskstats
-r--r--r--. 1 root root 0 Jun 18 11:35 meminfo
-r--r--r--. 1 root root 0 Jun 18 11:35 stat
-r--r--r--. 1 root root 0 Jun 18 11:35 swaps
-r--r--r--. 1 root root 0 Jun 18 11:35 uptime
```

```
[root@vz01 ~]# ls -al /var/lib/lxcfs/cgroup
total 0
drwxr-xr-x. 2 root root 0 Jun 18 11:36 .
drwxr-xr-x. 2 root root 0 Jun 18 11:36 ..
drwxr-xr-x. 2 root root 0 Jun 18 11:36 blkio
drwxr-xr-x. 2 root root 0 Jun 18 11:36 cpuacct,cpu
drwxr-xr-x. 2 root root 0 Jun 18 11:36 cpuset
drwxr-xr-x. 2 root root 0 Jun 18 11:36 devices
drwxr-xr-x. 2 root root 0 Jun 18 11:36 freezer
drwxr-xr-x. 2 root root 0 Jun 18 11:36 hugetlb
drwxr-xr-x. 2 root root 0 Jun 18 11:36 memory
drwxr-xr-x. 2 root root 0 Jun 18 11:36 name=systemd
drwxr-xr-x. 2 root root 0 Jun 18 11:36 net_prio,net_cls
drwxr-xr-x. 2 root root 0 Jun 18 11:36 perf_event
drwxr-xr-x. 2 root root 0 Jun 18 11:36 pids
```

```
[root@vz01 ~]# cat /proc/self/cgroup
11:freezer:/
10:devices:/user.slice
9:cpuacct,cpu:/user.slice
8:blkio:/user.slice
7:cpuset:/
6:pids:/
5:perf_event:/
4:memory:/user.slice
3:net_prio,net_cls:/
2:hugetlb:/
1:name=systemd:/user.slice/user-0.slice/session-92.scope
```

I'll recompile to master and repeat.

**Comment by tomponline** [comment] 2017-06-18 11:45
OK i switched back to master commit https://github.com/lxc/lxcfs/commit/389c86f1db2e7669ed0501ce90d700fe1e6a7f65

```
● lxcfs.service - FUSE filesystem for LXC
   Loaded: loaded (/usr/lib/systemd/system/lxcfs.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-06-18 11:42:30 UTC; 40s ago
     Docs: man:lxcfs(1)
 Main PID: 14403 (lxcfs)
   Memory: 924.0K
   CGroup: /system.slice/lxcfs.service
           └─14403 /usr/bin/lxcfs /var/lib/lxcfs/

Jun 18 11:42:30 vz01lxcfs[14403]: 3: fd:   8: blkio
Jun 18 11:42:30 vz01lxcfs[14403]: 4: fd:   9: cpuset
Jun 18 11:42:30 vz01lxcfs[14403]: 5: fd:  10: pids
Jun 18 11:42:30 vz01 lxcfs[14403]: 6: fd:  11: perf_event
Jun 18 11:42:30 vz01 xcfs[14403]: 7: fd:  12: memory
Jun 18 11:42:30 vz01 lxcfs[14403]: 8: fd:  13: net_prio,net_cls
Jun 18 11:42:30 vz01 lxcfs[14403]: 9: fd:  14: hugetlb
Jun 18 11:42:30 vz01 lxcfs[14403]: 10: fd:  15: name=systemd
Jun 18 11:42:56 vz01lxcfs[14403]: bindings.c: 3868: proc_uptime_read: failed to write to cache
Jun 18 11:42:56 vz01 lxcfs[14403]: bindings.c: 3868: proc_uptime_read: failed to write to cache
```

```
[root@vz01 ~]# ls -al /var/lib/lxcfs/proc
total 0
dr-xr-xr-x. 2 root root 0 Jun 18 11:44 .
drwxr-xr-x. 2 root root 0 Jun 18 11:44 ..
-r--r--r--. 1 root root 0 Jun 18 11:44 cpuinfo
-r--r--r--. 1 root root 0 Jun 18 11:44 diskstats
-r--r--r--. 1 root root 0 Jun 18 11:44 meminfo
-r--r--r--. 1 root root 0 Jun 18 11:44 stat
-r--r--r--. 1 root root 0 Jun 18 11:44 swaps
-r--r--r--. 1 root root 0 Jun 18 11:44 uptime
```

```
[root@vz01 ~]# ls -al /var/lib/lxcfs/cgroup
total 0
drwxr-xr-x. 2 root root 0 Jun 18 11:45 .
drwxr-xr-x. 2 root root 0 Jun 18 11:45 ..
drwxr-xr-x. 2 root root 0 Jun 18 11:45 blkio
drwxr-xr-x. 2 root root 0 Jun 18 11:45 cpuacct,cpu
drwxr-xr-x. 2 root root 0 Jun 18 11:45 cpuset
drwxr-xr-x. 2 root root 0 Jun 18 11:45 devices
drwxr-xr-x. 2 root root 0 Jun 18 11:45 freezer
drwxr-xr-x. 2 root root 0 Jun 18 11:45 hugetlb
drwxr-xr-x. 2 root root 0 Jun 18 11:45 memory
drwxr-xr-x. 2 root root 0 Jun 18 11:45 name=systemd
drwxr-xr-x. 2 root root 0 Jun 18 11:45 net_prio,net_cls
drwxr-xr-x. 2 root root 0 Jun 18 11:45 perf_event
drwxr-xr-x. 2 root root 0 Jun 18 11:45 pids
```

```
[root@vz01 ~]# cat /proc/self/cgroup
11:freezer:/
10:devices:/user.slice
9:cpuacct,cpu:/user.slice
8:blkio:/user.slice
7:cpuset:/
6:pids:/
5:perf_event:/
4:memory:/user.slice
3:net_prio,net_cls:/
2:hugetlb:/
1:name=systemd:/user.slice/user-0.slice/session-93.scope
```

**Comment by brauner** [comment] 2017-06-18 12:18
Ok, can you also give me: `cat /var/lib/lxcfs/proc/uptime`?

**Comment by tomponline** [comment] 2017-06-18 12:21
```
[root@vz01 ~]# cat /var/lib/lxcfs/proc/uptime
0.00 0.00
```

**Comment by tomponline** [comment] 2017-06-18 12:23
when I switch back to commit https://github.com/lxc/lxcfs/commit/e48e16dc588e1a7718453f06b0f7228d13cd2c84 it shows 

```
[root@vz01 ~]# cat /var/lib/lxcfs/proc/uptime
244752.0 237919.0
```

**Comment by brauner** [comment] 2017-06-18 12:24
@tomponline, cheers :)

**Comment by Pietia10** [comment] 2017-07-12 19:07
lxc 2.0.8 same issue on debian 9.0 container:
root@ct1:~# cat /proc/uptime
7.00 7.00
bad data in /proc/uptime
bad data in /proc/uptime

**Comment by hallyn** [comment] 2017-07-14 18:47
@brauner - do you know what's causing this?

**Comment by demaffias** [comment] 2017-07-24 15:15
I have the same issue on Ubuntu 17.04

 driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.10.0-28-generic
  server: lxd
  server_pid: 6028
  server_version: "2.15"

**Comment by Blub** [comment] 2017-08-01 06:32
Haven't checked the commits in this issue, but what happens is that top opens /proc/uptime once and reuses the file descriptor.
testcase:
```C
char buf[1024];
int fd = open("/proc/uptime", O_RDONLY);
printf("read() -> %i\n", read(fd, buf, sizeof(buf)));
lseek(fd, 0, SEEK_SET);
printf("read() -> %i\n", read(fd, buf, sizeof(buf)));
```
result inside a container:
```
read() -> 14
read() -> 0
```

The second read after rewinding returns no data.

**Comment by estint** [comment] 2017-08-26 12:37
happened to me too
bad data in /proc/uptime
2.17-0ubuntu2~ubuntu16.04.1~ppa1           amd64

**Comment by brauner** [comment] 2017-08-26 16:42
This should have been fixed in https://github.com/lxc/lxcfs/pull/205 .

**Closed by brauner** 2017-08-26 16:42 UTC

**Comment by C0rn3j** [comment] 2017-10-23 11:31
For those wondering which release fixed this - 

https://discuss.linuxcontainers.org/t/lxcfs-2-0-8-has-been-released/675

lxcfs 2.0.8 has been released few days ago and the issue is fixed in it

**Comment by zvpunry** [comment] 2018-01-04 15:16
Not really related to this bug but it has the same symptoms, so it might help someone who found this lxcfs issue:

If these symptoms (bad data in /proc/uptime, SIGFPE in "ps u") appear and the host system was copied using rsync from a running system, it may happen that /var/lib/lxcfs/* is full of empty files. This causes lxcfs to refuse to start with the following message:

Jan 04 08:00:00 redacted lxcfs[465]: fuse: mountpoint is not empty
Jan 04 08:00:00 redacted lxcfs[465]: fuse: if you are sure this is safe, use the 'nonempty' mount option

The solution is, check on the host system if lxcfs is running, if it isn't running and there are files in /var/lib/lxcfs/*, stop all lxc, rm -rf /var/lib/lxcfs/*, systemctl start lxcfs and now all files under /var/lib/lxcfs/* (like /var/lib/lxcfs/proc/uptime) should be OK. Then restart the lxc containers.

And the next time a running system is to be copied with rsync, use mount --bind / /tmp/root-rsync/ (or something like that) to get rid of all submounts (to not copy the content of virtual filesystems like lxcfs) and to make "hidden" directories available for the rsync. Or avoid copying a running system (but this can not always be avoided).

This happened on a debian stretch (9.3) machine with the debian lxc package (2.0.7-1) and guests running debian stretch (9.3).

**Comment by brauner** [comment] 2018-01-05 14:37
On Thu, Jan 04, 2018 at 03:16:15PM +0000, zvpunry wrote:
> Not really related to this bug but it has the same symptoms, so it
> might help someone who found this lxcfs issue:
> 
> If these symptoms (bad data in /proc/uptime, SIGFPE in "ps u") appear
> and the host system was copied using rsync from a running system, it
> may happen that /var/lib/lxcfs/* is full of empty files. This causes
> lxcfs to refuse to start with the following message:
> 
> Jan 04 08:00:00 redacted lxcfs[465]: fuse: mountpoint is not empty
> Jan 04 08:00:00 redacted lxcfs[465]: fuse: if you are sure this is safe, use the 'nonempty' mount option
> 
> The solution is, check on the host system if lxcfs is running, if it
> isn't running and there are files in /var/lib/lxcfs/*, stop all lxc,
> rm -rf /var/lib/lxcfs/*, systemctl start lxcfs and now all files under
> /var/lib/lxcfs/* (like /var/lib/lxcfs/proc/uptime) should be OK. Then
> restart the lxc containers.
> 
> And the next time a running system is to be copied with rsync, use
> mount --bind / /tmp/root-rsync/ (or something like that) to get rid of
> all submounts (to not copy the content of virtual filesystems like
> lxcfs) and to make "hidden" directories available for the rsync. Or
> avoid copying a running system (but this can not always be avoided).

Fwiw, you can also exclude /var/lib/lxcfs/* in your rsync options when
copying the system.

**Comment by zvpunry** [comment] 2018-01-05 15:41
It may seem easier to exclude some stuff, but the exclude list will never be complete, there is always one stupid thing that gets forgotten. The person who used rsync to copy that system used excludes, they contained all that sysfs,proc,tmpfs,cgroup stuff but he forgot lxcfs.

A mount bind is a nice way to make sure that only the file system you want to copy is copied, without any sub-mount or directories hidden below a mount-point. :-)
