### ISSUE TITLE
RAM report is incorrect.

### ISSUE THREAD

**Issue by loru** [lxc/lxcfs#120] opened 2016-06-15 14:42 UTC
# Required information
- Distribution: Ubuntu 16.04
- Distribution version: Ubuntu 16.04
  - Kernel version: 4.4.0-22-generic
  - LXD version: 2.0.2
  - Storage backend in use: ZFS
# Issue description

When a container is created, the ram reported in htop is alright, for example 4MB out of 256MB.

![screen shot 2016-06-06 at 5 04 59 pm](https://cloud.githubusercontent.com/assets/19887885/15990525/31bb1c1c-3095-11e6-8a1e-4dbe61a55d91.png)

But after some time, the ram report becomes incorrect:

![screen shot 2016-06-06 at 5 05 26 pm](https://cloud.githubusercontent.com/assets/19887885/15990527/428d33c2-3095-11e6-9ff7-faa401f6fb3b.png)

Container's meminfo:

```
MemTotal:         524288 kB
MemFree:          404444 kB
MemAvailable:     404444 kB
Buffers:               0 kB
Cached:           115540 kB
SwapCached:            0 kB
Active:           829940 kB
Inactive:         137444 kB
Active(anon):     110492 kB
Inactive(anon):    65644 kB
Active(file):     719448 kB
Inactive(file):    71800 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                56 kB
Writeback:             0 kB
AnonPages:         88216 kB
Mapped:            76532 kB
Shmem:             87872 kB
Slab:               0 kB
SReclaimable:     101908 kB
SUnreclaim:       701924 kB
KernelStack:       11440 kB
PageTables:         6332 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1983828 kB
Committed_AS:     643708 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:     26624 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      146020 kB
DirectMap2M:     3973120 kB

```
# Steps to reproduce
1. lxc create ubuntu:16.04 [your-container]
2. Wait for one or two days.
3. Run htop in the container.

Note: as suggested by @stgraber, I open this issue here but it has already been opened there with explanations:
https://github.com/lxc/lxd/issues/2108

I can not submit a patch, sysadmin but no dev, I do my part as much as I can.

**Comment by mjeanson** [comment] 2016-08-16 15:08
Same problem here, adding some info.

- Distribution: Ubuntu 16.04
- Distribution version: Ubuntu 16.04
 - Kernel version: 4.4.0-34-generic
 - LXD version: 2.0.3-0ubuntu1~ubuntu16.04.2
 - lxcfs version: 2.0.2-0ubuntu1~ubuntu16.04.1
 - Storage backend in use: ZFS

Container's meminfo:
```
MemTotal:        2097152 kB
MemFree:         1981836 kB
MemAvailable:    1981836 kB
Buffers:               0 kB
Cached:            75824 kB
SwapCached:            0 kB
Active:          5529604 kB
Inactive:         588320 kB
Active(anon):    4455404 kB
Inactive(anon):    80596 kB
Active(file):    1074200 kB
Inactive(file):   507724 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       2095096 kB
SwapFree:        2095096 kB
Dirty:                76 kB
Writeback:             0 kB
AnonPages:       4418608 kB
Mapped:           198956 kB
Shmem:            117488 kB
Slab:               0 kB
SReclaimable:     207316 kB
SUnreclaim:      2799256 kB
KernelStack:       14304 kB
PageTables:        32168 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    18551508 kB
Committed_AS:   12730568 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:   1630208 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      827744 kB
DirectMap2M:    13817856 kB
DirectMap1G:    20971520 kB
```

Containers /sys/fs/cgroup/memory/memory.*
```
/sys/fs/cgroup/memory/memory.failcnt
0
/sys/fs/cgroup/memory/memory.force_empty
/sys/fs/cgroup/memory/memory.kmem.failcnt
0
/sys/fs/cgroup/memory/memory.kmem.limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/memory.kmem.max_usage_in_bytes
0
/sys/fs/cgroup/memory/memory.kmem.slabinfo
slabinfo - version: 2.1
# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> : tunables <limit> <batchcount> <sharedfactor> : slabdata <active_slabs> <num_slabs> <sharedavail>
/sys/fs/cgroup/memory/memory.kmem.tcp.failcnt
0
/sys/fs/cgroup/memory/memory.kmem.tcp.limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/memory.kmem.tcp.max_usage_in_bytes
0
/sys/fs/cgroup/memory/memory.kmem.tcp.usage_in_bytes
0
/sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
0
/sys/fs/cgroup/memory/memory.limit_in_bytes
2147483648
/sys/fs/cgroup/memory/memory.max_usage_in_bytes
258514944
/sys/fs/cgroup/memory/memory.move_charge_at_immigrate
0
/sys/fs/cgroup/memory/memory.numa_stat
total=5356 N0=5356
file=5081 N0=5081
anon=275 N0=275
unevictable=0 N0=0
hierarchical_total=28802 N0=28802
hierarchical_file=14766 N0=14766
hierarchical_anon=14036 N0=14036
hierarchical_unevictable=0 N0=0
/sys/fs/cgroup/memory/memory.oom_control
oom_kill_disable 0
under_oom 0
/sys/fs/cgroup/memory/memory.pressure_level
/sys/fs/cgroup/memory/memory.soft_limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/memory.stat
cache 20815872
rss 1249280
rss_huge 0
mapped_file 98304
dirty 0
writeback 0
pgpgin 716423
pgpgout 722278
pgfault 1377219
pgmajfault 82692
inactive_anon 0
active_anon 1146880
inactive_file 9138176
active_file 11673600
unevictable 0
hierarchical_memory_limit 2147483648
total_cache 77705216
total_rss 40394752
total_rss_huge 0
total_mapped_file 13582336
total_dirty 0
total_writeback 0
total_pgpgin 2023483
total_pgpgout 2069256
total_pgfault 3837424
total_pgmajfault 178084
total_inactive_anon 16912384
total_active_anon 40599552
total_inactive_file 11452416
total_active_file 49029120
total_unevictable 0
/sys/fs/cgroup/memory/memory.swappiness
0
/sys/fs/cgroup/memory/memory.usage_in_bytes
118534144
/sys/fs/cgroup/memory/memory.use_hierarchy
1
```

**Comment by hallyn** [comment] 2016-08-20 22:40
I tried to reproduce this but failed.  Could you, when the reported
memory usage starts to go up, show the contents of the memory.stat
file in /sys/fs/cgroup/memory/$(container cgroup) ?

**Comment by hallyn** [comment] 2016-08-20 22:41
Sorry I see you already did that.

**Comment by hallyn** [comment] 2016-08-20 22:46
No, you showed the values for the top level.

Please show the results under /sys/fs/cgroup/memory/lxc/$(containername)

My guess is going to be that this has to do with the zfs backend.  I
seem to recall other mention of zfs kernel memory being accounted to
the user.

**Comment by loru** [comment] 2016-08-21 09:55
Hi,

I am not quite sure but it seems like when the container is using less than 1MB of ram, htop goes weird when showing the ram usage.
You can probably reproduce it easily: create a ubuntu container, remove everything that is using ram (log, snapd and so on) and then you will see htop showing 16.0Z

If it is not related to lxc, we should close this issue, no?

**Comment by stgraber** [comment] 2016-08-21 15:13
@hallyn I was around @mjeanson when he filed the bug. The values reported are for /sys/fs/cgroup/* inside the container on a system using cgroup namespaces and after confirming that the shell in the container was indeed at the root of the cgroup namespace.


This can be confirmed by looking at limit_in_bytes which shows a limit being applied that wouldn't be there was this captured from the root of the memory cgroup tree on the host.

**Comment by mjeanson** [comment] 2016-08-26 19:13
I noticed a similar behavior on another host.

Here is the container vmstat
````
root@ci-slave-i386-03-02:~# cat /proc/vmstat 
nr_free_pages 11301711
nr_alloc_batch 1889
nr_inactive_anon 1072395
nr_active_anon 2200003
nr_inactive_file 378763
nr_active_file 4583421
nr_unevictable 0
nr_mlock 0
nr_anon_pages 3178888
nr_mapped 133471
nr_file_pages 5070514
nr_dirty 48
nr_writeback 2
nr_slab_reclaimable 396953
nr_slab_unreclaimable 3164727
nr_page_table_pages 17006
nr_kernel_stack 2894
nr_unstable 0
nr_bounce 0
nr_vmscan_write 537090
nr_vmscan_immediate_reclaim 9237
nr_writeback_temp 0
nr_isolated_anon 0
nr_isolated_file 0
nr_shmem 62206
nr_dirtied 14928157
nr_written 15336819
nr_pages_scanned 0
numa_hit 23721932465
numa_miss 1407601
numa_foreign 1407601
numa_interleave 77371
numa_local 23721883345
numa_other 1456721
workingset_refault 3534664
workingset_activate 1126145
workingset_nodereclaim 0
nr_anon_transparent_hugepages 4227
nr_free_cma 0
nr_dirty_threshold 3232735
nr_dirty_background_threshold 1616367
pgpgin 15577969
pgpgout 2836295160
pswpin 195972
pswpout 537090
pgalloc_dma 0
pgalloc_dma32 158415525
pgalloc_normal 24973179261
pgalloc_movable 0
pgfree 25163358614
pgactivate 66960309
pgdeactivate 13598226
pgfault 30284063507
pgmajfault 111746995
pgrefill_dma 0
pgrefill_dma32 159853
pgrefill_normal 7784958
pgrefill_movable 0
pgsteal_kswapd_dma 0
pgsteal_kswapd_dma32 0
pgsteal_kswapd_normal 0
pgsteal_kswapd_movable 0
pgsteal_direct_dma 0
pgsteal_direct_dma32 0
pgsteal_direct_normal 2419
pgsteal_direct_movable 0
pgscan_kswapd_dma 0
pgscan_kswapd_dma32 0
pgscan_kswapd_normal 0
pgscan_kswapd_movable 0
pgscan_direct_dma 0
pgscan_direct_dma32 0
pgscan_direct_normal 3006
pgscan_direct_movable 0
pgscan_direct_throttle 0
zone_reclaim_failed 0
pginodesteal 0
slabs_scanned 11776
kswapd_inodesteal 0
kswapd_low_wmark_hit_quickly 0
kswapd_high_wmark_hit_quickly 0
pageoutrun 2
allocstall 237500
pgrotated 531553
drop_pagecache 0
drop_slab 0
numa_pte_updates 6352012046
numa_huge_pte_updates 3464351
numa_hint_faults 3084767973
numa_hint_faults_local 2735171780
numa_pages_migrated 276694682
pgmigrate_success 296671839
pgmigrate_fail 51663114
compact_migrate_scanned 178220849
compact_free_scanned 11625501783
compact_isolated 42734702
compact_stall 512400
compact_fail 502637
compact_success 9763
htlb_buddy_alloc_success 0
htlb_buddy_alloc_fail 0
unevictable_pgs_culled 0
unevictable_pgs_scanned 0
unevictable_pgs_rescued 0
unevictable_pgs_mlocked 0
unevictable_pgs_munlocked 0
unevictable_pgs_cleared 0
unevictable_pgs_stranded 0
thp_fault_alloc 697162
thp_fault_fallback 274928
thp_collapse_alloc 12942
thp_collapse_alloc_failed 851
thp_split 42497
thp_zero_page_alloc 1
thp_zero_page_alloc_failed 0
balloon_inflate 0
balloon_deflate 0
balloon_migrate 0
````

And here is the memory cgroup of the container from the host :
````
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/cgroup.clone_children
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/cgroup.event_control
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/cgroup.event_control: Invalid argument
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/cgroup.procs
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/init.scope
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/init.scope: Is a directory
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.failcnt
52501
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.force_empty
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.force_empty: Invalid argument
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.failcnt
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.max_usage_in_bytes
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.slabinfo
slabinfo - version: 2.1
# name            <active_objs> <num_objs> <objsize> <objperslab> <pagesperslab> : tunables <limit> <batchcount> <sharedfactor> : slabdata <active_slabs> <num_slabs> <sharedavail>
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.tcp.failcnt
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.tcp.limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.tcp.max_usage_in_bytes
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.tcp.usage_in_bytes
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.kmem.usage_in_bytes
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.limit_in_bytes
4294967296
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.max_usage_in_bytes
4294967296
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.move_charge_at_immigrate
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.numa_stat
total=18 N0=15 N1=3
file=3 N0=3 N1=0
anon=15 N0=12 N1=3
unevictable=0 N0=0 N1=0
hierarchical_total=359524 N0=295810 N1=63714
hierarchical_file=241473 N0=184430 N1=57043
hierarchical_anon=118051 N0=111380 N1=6671
hierarchical_unevictable=0 N0=0 N1=0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.oom_control
oom_kill_disable 0
under_oom 0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.pressure_level
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.pressure_level: Invalid argument
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.soft_limit_in_bytes
9223372036854771712
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.stat
cache 16384
rss 57344
rss_huge 0
mapped_file 4096
dirty 0
writeback 0
pgpgin 4121
pgpgout 4103
pgfault 7708
pgmajfault 970
inactive_anon 53248
active_anon 8192
inactive_file 8192
active_file 4096
unevictable 0
hierarchical_memory_limit 4294967296
total_cache 998412288
total_rss 474279936
total_rss_huge 348127232
total_mapped_file 31199232
total_dirty 8192
total_writeback 16384
total_pgpgin 671585618
total_pgpgout 671978777
total_pgfault 1022346382
total_pgmajfault 5575803
total_inactive_anon 331415552
total_active_anon 152121344
total_inactive_file 80928768
total_active_file 908144640
total_unevictable 0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.swappiness
60
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.usage_in_bytes
1473122304
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/memory.use_hierarchy
1
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/notify_on_release
0
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/system.slice
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/system.slice: Is a directory
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/tasks
/sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/user.slice
cat: /sys/fs/cgroup/memory/lxc/ci-slave-i386-03-02/user.slice: Is a directory
````

**Comment by hallyn** [comment] 2016-08-26 19:28
So in this case if i read it correctly the max usage in bytes is about 1/4 of the limit in bytes?  can you show /proc/meminfo in the container?

**Comment by mjeanson** [comment] 2016-08-26 19:35
````
root@ci-slave-i386-03-02:~# cat /proc/meminfo
MemTotal:        4194304 kB
MemFree:         2716972 kB
MemAvailable:    2716972 kB
Buffers:               0 kB
Cached:          1009692 kB
SwapCached:            0 kB
Active:         27635424 kB
Inactive:        6320956 kB
Active(anon):    8803716 kB
Inactive(anon):  4290860 kB
Active(file):   18831708 kB
Inactive(file):  2030096 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       3743316 kB
SwapFree:        2680184 kB
Dirty:               220 kB
Writeback:             8 kB
AnonPages:      12719924 kB
Mapped:           539364 kB
Shmem:            249032 kB
Slab:               0 kB
SReclaimable:    1658088 kB
SUnreclaim:     12660380 kB
KernelStack:       46496 kB
PageTables:        67948 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    69707136 kB
Committed_AS:   39811304 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:   8660992 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:     1373948 kB
DirectMap2M:    107571200 kB
DirectMap1G:    27262976 kB
````

**Comment by hallyn** [comment] 2016-08-26 19:38
So at least memtotal and memfree are correct there, right?  Most of the other fields in meminfo *should* look better with current git HEAD.  With the exception of VmallocTotal which I'm not sure how to handle.

**Comment by ssmax** [comment] 2017-01-17 16:38
this issue is very easy to reproduce under multiple lxc instances...
my situation:
debian 8.7 jessie
lxc-1.0.6
lxcfs-2.0.5

lxc-create two instances with the same settings:

lxc.autodev = 1
lxc.kmsg = 0
lxc.cgroup.memory.limit_in_bytes = 32G
lxc.cgroup.memory.memsw.limit_in_bytes = 32G
lxc.cgroup.memory.soft_limit_in_bytes = 32G
lxc.mount.auto = cgroup:mixed

lxc-start them

at this time , the meminfo is correct:
> head /proc/meminfo
MemTotal:       33554432 kB
MemFree:        33537652 kB
MemAvailable:   33537652 kB
Buffers:               0 kB
Cached:                0 kB
SwapCached:            0 kB
Active:             7644 kB
Inactive:              0 kB
Active(anon):       7612 kB
Inactive(anon):        0 kB


after 2 hours later...
lxc-console connect , you will find the meminfo is already incorrect, it shows the mem of host (128G)
> head /proc/meminfo
MemTotal:       132190572 kB
MemFree:        129033916 kB
MemAvailable:   129033916 kB
Buffers:               0 kB
Cached:               33 kB
SwapCached:            0 kB
Active:          1125000 kB
Inactive:              0 kB
Active(anon):      41132 kB
Inactive(anon):        0 kB

but meminfo will fix after instance reboot.

i have try lxcfs-0.18 / 2.0.1 / 2.0.5 with lxc-1.0.6, this issue is always appear after several hours.

**Comment by theredcat** [comment] 2017-01-30 09:47
Seems that #163 is the same problem

**Comment by ssmax** [comment] 2017-02-08 11:08
I think it is not the same problem,

just right after lxc boot,  /sys/fs/cgroup/memory/ only contains instance
file:

>find  /sys/fs/cgroup/memory/
/sys/fs/cgroup/memory/
/sys/fs/cgroup/memory/lxc
/sys/fs/cgroup/memory/lxc/231
/sys/fs/cgroup/memory/lxc/231/memory.pressure_level
/sys/fs/cgroup/memory/lxc/231/memory.use_hierarchy
/sys/fs/cgroup/memory/lxc/231/memory.swappiness
/sys/fs/cgroup/memory/lxc/231/memory.memsw.failcnt
/sys/fs/cgroup/memory/lxc/231/tasks
/sys/fs/cgroup/memory/lxc/231/memory.limit_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.memsw.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/cgroup.procs
/sys/fs/cgroup/memory/lxc/231/memory.usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.memsw.limit_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.failcnt
/sys/fs/cgroup/memory/lxc/231/memory.force_empty
/sys/fs/cgroup/memory/lxc/231/memory.memsw.usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.numa_stat
/sys/fs/cgroup/memory/lxc/231/cgroup.clone_children
/sys/fs/cgroup/memory/lxc/231/memory.oom_control
/sys/fs/cgroup/memory/lxc/231/notify_on_release
/sys/fs/cgroup/memory/lxc/231/memory.stat
/sys/fs/cgroup/memory/lxc/231/cgroup.event_control
/sys/fs/cgroup/memory/lxc/231/memory.move_charge_at_immigrate
/sys/fs/cgroup/memory/lxc/231/memory.soft_limit_in_bytes


at this time , the memory is correct
but after a few hours, /sys/fs/cgroup/memory/ will contain the main host
files.
it seem it's remounted by some one, and then the memory is incorrect.

/sys/fs/cgroup/memory/
/sys/fs/cgroup/memory/memory.pressure_level
/sys/fs/cgroup/memory/memory.use_hierarchy
/sys/fs/cgroup/memory/memory.swappiness
/sys/fs/cgroup/memory/memory.memsw.failcnt
/sys/fs/cgroup/memory/tasks
/sys/fs/cgroup/memory/memory.limit_in_bytes
/sys/fs/cgroup/memory/memory.memsw.max_usage_in_bytes
/sys/fs/cgroup/memory/cgroup.procs
/sys/fs/cgroup/memory/release_agent
/sys/fs/cgroup/memory/memory.usage_in_bytes
/sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
/sys/fs/cgroup/memory/memory.failcnt
/sys/fs/cgroup/memory/memory.force_empty
/sys/fs/cgroup/memory/memory.memsw.usage_in_bytes
/sys/fs/cgroup/memory/memory.max_usage_in_bytes
/sys/fs/cgroup/memory/memory.numa_stat
/sys/fs/cgroup/memory/cgroup.clone_children
/sys/fs/cgroup/memory/memory.oom_control
/sys/fs/cgroup/memory/cgroup.sane_behavior
/sys/fs/cgroup/memory/notify_on_release
/sys/fs/cgroup/memory/memory.stat
/sys/fs/cgroup/memory/cgroup.event_control
/sys/fs/cgroup/memory/memory.move_charge_at_immigrate
/sys/fs/cgroup/memory/memory.soft_limit_in_bytes
/sys/fs/cgroup/memory/lxc
/sys/fs/cgroup/memory/lxc/memory.pressure_level
/sys/fs/cgroup/memory/lxc/memory.use_hierarchy
/sys/fs/cgroup/memory/lxc/memory.swappiness
/sys/fs/cgroup/memory/lxc/memory.memsw.failcnt
/sys/fs/cgroup/memory/lxc/tasks
/sys/fs/cgroup/memory/lxc/memory.limit_in_bytes
/sys/fs/cgroup/memory/lxc/memory.memsw.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/cgroup.procs
/sys/fs/cgroup/memory/lxc/memory.usage_in_bytes
/sys/fs/cgroup/memory/lxc/memory.memsw.limit_in_bytes
/sys/fs/cgroup/memory/lxc/memory.failcnt
/sys/fs/cgroup/memory/lxc/memory.force_empty
/sys/fs/cgroup/memory/lxc/memory.memsw.usage_in_bytes
/sys/fs/cgroup/memory/lxc/memory.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/memory.numa_stat
/sys/fs/cgroup/memory/lxc/cgroup.clone_children
/sys/fs/cgroup/memory/lxc/memory.oom_control
/sys/fs/cgroup/memory/lxc/notify_on_release
/sys/fs/cgroup/memory/lxc/memory.stat
/sys/fs/cgroup/memory/lxc/cgroup.event_control
/sys/fs/cgroup/memory/lxc/memory.move_charge_at_immigrate
/sys/fs/cgroup/memory/lxc/memory.soft_limit_in_bytes
/sys/fs/cgroup/memory/lxc/231
/sys/fs/cgroup/memory/lxc/231/memory.pressure_level
/sys/fs/cgroup/memory/lxc/231/memory.use_hierarchy
/sys/fs/cgroup/memory/lxc/231/memory.swappiness
/sys/fs/cgroup/memory/lxc/231/memory.memsw.failcnt
/sys/fs/cgroup/memory/lxc/231/tasks
/sys/fs/cgroup/memory/lxc/231/memory.limit_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.memsw.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/cgroup.procs
/sys/fs/cgroup/memory/lxc/231/memory.usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.memsw.limit_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.failcnt
/sys/fs/cgroup/memory/lxc/231/memory.force_empty
/sys/fs/cgroup/memory/lxc/231/memory.memsw.usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.max_usage_in_bytes
/sys/fs/cgroup/memory/lxc/231/memory.numa_stat
/sys/fs/cgroup/memory/lxc/231/cgroup.clone_children
/sys/fs/cgroup/memory/lxc/231/memory.oom_control
/sys/fs/cgroup/memory/lxc/231/notify_on_release
/sys/fs/cgroup/memory/lxc/231/memory.stat
/sys/fs/cgroup/memory/lxc/231/cgroup.event_control
/sys/fs/cgroup/memory/lxc/231/memory.move_charge_at_immigrate
/sys/fs/cgroup/memory/lxc/231/memory.soft_limit_in_bytes





2017年1月30日 17:47，"Nathan Delhaye" <notifications@github.com>写道：

**Comment by hackel** [comment] 2017-03-01 20:25
No idea if this is the same issue, but I just discovered that my container has 9.2 exabytes available.  From /proc/meminfo:
```
SwapTotal:      9007199238383524 kB
SwapFree:       9007199238090352 kB
```
Other values appear to be correct.  The host only has a 16G swap partition, plus another 8G of zram.  lxc 2.9.3, lxcfc 2.0.6.

**Comment by mvaessen** [comment] 2017-04-16 20:28
Same issue as Hackel. Fresh installed machine.
Storage: ZFS
OS: Ubuntu 16.04.2
Kernel: 4.4.0-72-generic

`SwapTotal:      9007199189127940 kB
SwapFree:       9007199189127940 kB`

Host has 18GB swap partition.
LXC: 2.0.9, LXCFS: 2.0.6

**Comment by qwertyx64** [comment] 2017-05-19 12:46
Same issue only with Ubuntu :-/

**Comment by tebanep** [comment] 2018-04-04 15:17
This issue seems to be fixed by commit ad19b86d22ef75e1dac0ae9cc564089102ec043a. Containers use swap memory unnecessarily because of this mismatch. @stgraber will version 2.0.9 be released any time soon? Thanks a lot for LXC, LXD and LXCFS!

**Comment by tebanep** [comment] 2018-04-27 00:26
Can we expect any bugfix release soon for the 2.0.x @stgraber?

**Comment by brauner** [comment] 2018-06-11 10:40
New versions have been released which include the requested fix.

**Closed by brauner** 2018-06-11 10:40 UTC
